### ISSUE TITLE
Change color of a paragraph

### ISSUE THREAD

**Issue by Elen93** [soztag/fossos#55] opened 2018-10-18 10:01 UTC
I would suggest changing the color of the paragraph "Related Class: Introduction to R". The green color makes it a little difficult to read the links! Maybe another shade of green or a completely different color.

**Comment by maxheld83** [comment] 2018-10-31 16:41
I'm going to close this, because it's kinda a duplicate of #59.
In #59, the color scheme should be reworked generally, so this would kinda be a special case of that.

**Closed by maxheld83** 2018-10-31 16:41 UTC
Labels: class website, duplicate, pass/fail, software carpentry
